### ISSUE TITLE
Issue with minimizing "master" window with 2 monitors

### ISSUE THREAD

**Issue by alexjp** [esjeon/krohnkite#13]
Hi,

I have two monitors. When I open two windows on monitor 1 ( and have monitor 2 empty ) in tiled mode ( windows become side by side ), and I minimize the master window, the "other" window turns full window size on monitor 2, not monitor 1.

So, hoping that its clear, when I minimize master window on monitor 1, the other window will move to the other monitor. Note that this, during my testing, only happens when having only two windows ( the other monitor can be empty or not ).

Thanks for the awesome script, have been using it for days now !

**Comment by esjeon** [comment]
Okay, I figured out the source of the problem.

Surprise, surprise. KWin script is invoked concurrently, causing race conditions. Here's what exactly happened:

1. Minimizing the master fires `client.minimizeChanged` signal, which causes full rearrangement of all tiles.
2. During the rearrangement of `screen 0`, the slave is resized and move. Due to the order of operations (resize->move), the slave temporarily invades `screen 1` (Of course, this depends on monitor configuration).
3. KWin thinks the slave is move to `screen 1`, and fires `client.screenChanged` signal **concurrently**. This causes another full rearrangement being performed concurrently, and, for some reason, the first rearrangement is effectively suspended.
4. The second rearrangement tiles the slave to `screen 1`, and completes.
5. The first rearrangement continues to `screen 1`, tiles the slave again,  and completes.

Preventing the race condition did fix the problem, but I think I should find a better solution than adding an arbitrary flag.

**Comment by esjeon** [comment]
I pushed a fix 87d96833b85150a3143d61ae1730d1741d26f6ad. Instead of tackling with race condition, I could suppress it once for all. This will also prevent windows being randomly thrown into another screen.

I did test this in multi-head VM, but would you check if it indeed works?

**Comment by alexjp** [comment]
I haven't done extensive testing yet, but doing simple 2 windows setups with minimizing the master, it doesn't move windows, in both monitors.

Seems good :) Thanks for your awesome work !

**Comment by esjeon** [comment]
Okay, thanks. Closing now.
