### ISSUE TITLE
Some program do not open as tiles and pressing the Float shortcut doesn't put them back to tile

### ISSUE THREAD

**Issue by TheBats** [esjeon/krohnkite#179]
**Symptom**
Newly opened windows are not always opened in tilling mode and pressing Meta+F (assigned to Float) doesn't solve the issue.

**How to Reproduce**
1. Open a program (Tested with Sublime and Octave)
2. When it opens in floating mode try pressing the Float shortcut 

**Expected behavior**
The opened windows should open as a tile and pressing the "Float" shortcut should put it back to tile or float.

**Environment**
 - Manjaro
 - KWin version: 5.22.3
 - Krohnkite version: 0.8
 - List of KWin scripts in use: Krohnkite is the only one I use

**Notes**
Thank you for working on Krohnkite, I used it for a few months now and can't imagine using KDE without it

**Comment by ThomasDNguyen** [comment]
Hey, I'm not the dev but maybe I can help you. I do need to ask some questions to clarify, though: 
1. Not opened in tilling how? as in it's in float mode or something else? There are several tilling types/options, and certain window rules for certain window types can cause a variety of unwanted outcomes. There are several ways a window(s) can stop tilling, can you provide pictures of the un-tiled windows and your krohnkite settings?
2. Are those by chance Utility windows (windows that have window type: Dialog, Splash, Utility)? because utility windows are set to float. See [picture](https://i.imgur.com/83NfD1k.png)
**NOTE**: Also, the fastest and easiest way to solve most of the tiling problems is to perform a reset on krohnkite script `Untick Krohnkite` -> `Apply` -> `Tick Krohnkite` -> Apply.

**Comment by TheBats** [comment]
I moved to KDE 5.22.4 since then and it seems to have fixed all the issues I had.
