### ISSUE TITLE
[feature request] separate shortcuts for move focus, move border and move window

### ISSUE THREAD

**Issue by qiaojunfeng** [esjeon/krohnkite#36]
After testing many kwin scripts capable of tiling window, I find krohnkite is the most satisfying one for me, thank you for your marvelous code! 

However, I found the shortcuts somewhat confusing. 
I can use `Meta + J` and `Meta + K` for moving focus, but it seems that `Meta + H` and `Meta + L` are used for moving the border of the window (i.e. expanding or shrinking the currently focused window). 
As a `vi` user, I am accustomed to using `h j k l` as directions, so what about changing the shortcuts(or make the settings customizable) as follows?
1. move focus
    `Meta + H`: focus goes left
    `Meta + J`: focus goes down
    `Meta + K`: focus goes up
    `Meta + L`: focus goes right

2. move border
    `Meta + Shift + H`: border goes left
    `Meta + Shift + J`: border goes down
    `Meta + Shift + K`: border goes up
    `Meta + Shift + L`: border goes right

3. move window
    `Meta + Ctrl + H`: move window to left
    `Meta + Ctrl + J`: move window to down
    `Meta + Ctrl + K`: move window to up
    `Meta + Ctrl + L`: move window to right

By the way, a small question: can we control how a new window is placed(below or on the right of the exsiting window)? Thanks!

**Comment by esjeon** [comment]
Yeah, thanks for suggesting. This was something that always in my mind.

I too think `Meta+HJKL` should be used for moving focus alone. The current DWM-like behaviour isn't that bad, but some layouts (in the future) can surely benefit from i3-like behaviour. I initially thought i3-like layout/behaviour would  be impossible in Krohnkite due to its design decision, but I was quite wrong.

Also, I was trying to get away with KWin built-in shortcut for moving focus (to left/right/up/down), but it sometimes provides subpar experience. The best option is to let each layout perform focus changing individually.

But I think `Meta+Shift` should be used for moving windows, which is what i3 also does. `Shift` is easier to press, and shifting literally means moving.

> By the way, a small question: can we control how a new window is placed(below or on the right of the exsiting window)?

Will not be impossible, but I cannot come up w/ a generalized behaviour that works across different layouts.

**Comment by qiaojunfeng** [comment]
Wow, it's very nice to hear that you are considering the same issue, can't wait to play with the next release! Thank you!

**Comment by esjeon** [comment]
Commit a86701a077da6ff40400cd92383844beb6dda383 implements configurable HJKL behaviors, and, if "focus" mode is used, Krohnkite can move focus to user specified direction, just like i3.

**Comment by esjeon** [comment]
Closing. The shortcuts have been added and performed stable for a while.
