### ISSUE TITLE
key bindings not working

### ISSUE THREAD

**Issue by alexxxmg** [esjeon/krohnkite#50]
I'm sorry if it is the wrong place to ask this, but I cannot find any sort of manual on how to use krohnkite...
I'm a newbie but wanted really bad to test a tiling wm so I installed it: flawless, I like it very much (Fedora KDE here).
My problem is that I cannot find a way to use the key bindings: none works.
It is possible that I do not understand which the META key is, but I tried both Alt and Ctrl...

can somebody suggest me something?

Thanks!

**Comment by esjeon** [comment]
Well, not your fault, since **Meta key** is [a key used to be on keyboards *long long time ago*](https://askubuntu.com/questions/19558/what-are-the-meta-super-and-hyper-keys). It doesn't exist anymore on modern keyboards, but X11 (the graphics server) still uses the term to refer to either <kbd>Windows</kbd> or <kbd>Command</kbd> (on Apple keyboards).

If your keyboard lacks this "Meta key", either you should remap all the keybindings for Krohnkite in System Settings, or edit the following line in the source code to use Alt, Ctrl or anything that works for you:
https://github.com/esjeon/krohnkite/blob/577fc7f55082a6ec0dfc1090c12b79dbb9450398/src/driver/kwin/kwindriver.ts#L117
There might be a better solution, but finding one might take some time.

**Comment by alexxxmg** [comment]
Thanks for your help, I found everything in SysSettings>Shortcuts>Global>Kwin>Krohnkite
It is still not clear to me what many of those actions are, but I'm experimenting...
