### ISSUE TITLE
conky goes above windows but it goes below when windows are floating in

### ISSUE THREAD

**Issue by talentlessguy** [esjeon/krohnkite#58]
**Symptom**

conky goes above windows but it goes below when windows are floating.

**How to Reproduce**
1. Launch Krohnkite
2. Launch `conky` with any config including this:

```
own_window = true,
own_window_transparent = true,
own_window_type = 'dock',
own_window_class = 'Conky',
own_window_argb_visual = true,
```
3. See conky above windows

**Expected behavior**
Conky should run below windows, because it hides when window is in floating mode.

**Environment**
 - Distro: Manjaro Linux
 - KWin version: 5.17.5
 - Krohnkite version: 0.5
 - List of KWin scripts in use: MinimizeAll

**Screenshots**

![image](https://user-images.githubusercontent.com/35937217/73474404-7e892680-439f-11ea-9ee4-5cece8ce7a6d.png)
![image](https://user-images.githubusercontent.com/35937217/73474485-9bbdf500-439f-11ea-91a2-232bc60cf38e.png)

**Comment by esjeon** [comment]
I think it's because Krohnkite sets "keepBelow" for tiled windows. Try disabling "Keep tile windows below" under "Options" tab in the script configuration.

Maybe it's better to keep floating windows "above" than to keep tiled windows "below", because "keep below" is legitimately used in other parts of desktop environments.

**Comment by talentlessguy** [comment]
@esjeon I can't find the option `keepBelow` :/

![image](https://user-images.githubusercontent.com/35937217/73479998-125ff000-43aa-11ea-801e-58308238838c.png)

**Comment by esjeon** [comment]
Oh, you're using v0.5. I was thinking of master branch, which is 1 year ahead of it. I really have to release a new version...

Meanwhile, you can try git version if you want.

**Comment by talentlessguy** [comment]
@esjeon I'll better wait till you make a github release :sweat_smile:

**Comment by esjeon** [comment]
Yup, I'm actually rushing now. I'm gonna release it today. I actually wanted to write proper documentation and fully implement unit tests before 0.6, but people are basically one year behind... That's really bad...

**Comment by esjeon** [comment]
Sorry, I completely forgot to mention the release here. v0.6 is uploaded to the KDE store, and this problem should be gone by default.

**Comment by talentlessguy** [comment]
@esjeon I updated it but it is still v0.5 :thinking: 

I'll try installing krohnkite from github then

**Comment by talentlessguy** [comment]
Installed from repo, conky is still above the tiling window, with or without "keep above" setting enabled.

**Comment by esjeon** [comment]
Is "Keep Below" set for tiled windows? You can check this from "More Actions" under window action menu(Alt+F3 or R-click on title bar). If it's still set, it's likely that the script is cached by KWin. Try restarting KWin or just re-login.

**Comment by talentlessguy** [comment]
I tried both disabling and enabling the setting, restarting kwin. `conky` is still above all windows, except not tiling ones.

**Comment by esjeon** [comment]
Oh, btw, `dock` type doesn't set the "Keep Below" by default. You must set window hints manually:

        own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager'

I should've inspected it more carefully. I always copy-paste conky setting, so never realized this line has been there. lol

**Comment by talentlessguy** [comment]
@esjeon it still happens, even with `own_window_hints`, but when u focus on a window it goes below

so it is 50% working, but should go to background without having to focus on a window

**Comment by esjeon** [comment]
Hmm, it seems like [KWin is internally ignoring "keep below" for docks](https://github.com/KDE/kwin/blob/fb114dfba3717d63e65cf5c221f5457e64ea8efa/placement.cpp#L265). Yet, this issue has been largely ignored, probably because it doesn't matter if conky is the first program launched and naturally placed at the bottom.

I think the only sane way to keep conky below is this:
1. `own_window_type=normal` 
2. `own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager'`
3. add `conky` to ignored classes in Krohnkite settings.

**Comment by neurofire80** [comment]
Works for me if in conky, set:
1. ```background=true```
2. ```own_window_type=`override` ```
