### ISSUE TITLE
"Float all" should make next appearing window float, too

### ISSUE THREAD

**Issue by mpsdskd** [esjeon/krohnkite#60]
**Symptom**
"Float all" should make next appearing window float, too.
Basically I want to be able to enable/disable krohnkite via "Float all"

**How to Reproduce**
1. Have windows
2. Toggle "float all"
3. Create new window
4. New window is tiled/doesn't float

**Expected behavior**
New window should float, too. Oftentimes tiling windows are increadibly practical, but sometimes they are not. Completely switching between both modes, is what I expect *Toggle Float All* expect to do. 

**Environment**
 - Distro: [Kubuntu 19.04]
 - KWin version: [e.g. 5.12.9]
 - Krohnkite version: [0.6.1]
 - List of KWin scripts in use: No other scripts activated

**Notes**
Thank you very much for your work!

**Comment by esjeon** [comment]
For disabling tiling for all windows, you can use Floating Layout shortcut, which is unbound by default. Krohnkite internally uses this layout on screens and activities ignored by rules.

I know, this layout-centric model (inherited from dwm) can be confusing. I'm planning to make all this more user-friendly, but doing so will break user configs and shortcuts (due to limitations of KWin). I'll postpone this major breaking change until a major version update.

**Comment by mpsdskd** [comment]
Thank you very much, this is exactly, what I'm looking for, just not where I was looking for it.
Feeling a bit stupid now :D
