### ISSUE TITLE
Feature Request:  Separate layout for each workspace

### ISSUE THREAD

**Issue by oleks12345** [esjeon/krohnkite#71]
Hi, could you consider separating layout on each workspace, so let's say:
I can have one workspace with 1 master, and other one with 2 masters, or just different sizes of windows on each workspace.

**Comment by esjeon** [comment]
You already can configure this behavior in the script settings. Simply check "Use separate layouts for each Desktop" or "... Activity", and restart the script.

But I think I should change the default behavior, since most other WMs agree on using separate layouts by default.

Please keep this issue open, so that I don't forget changing it.

**Comment by oleks12345** [comment]
I can't see settings button
![image](https://user-images.githubusercontent.com/19672992/79029839-7ebf5280-7b96-11ea-95f9-720ebcdfc7ca.png)

**Comment by oleks12345** [comment]
In other script I was using there were a button on right with settings, where I can find setting for krohnkite

**Comment by oleks12345** [comment]
Sorry, I missed the part in README about user configs

**Comment by esjeon** [comment]
Closing. The default is changed in v0.8.
