### ISSUE TITLE
Move to next/previous window according to order of window at taskbar

### ISSUE THREAD

**Issue by zyf0330** [esjeon/krohnkite#87]
If this feature "move to next/previous window" is according to windows order at taskbar, it is good.

**Comment by esjeon** [comment]
A disappointing news.

I just did some experiments, but it turned out that window ordering in taskbar happens *locally*. That is, the order that windows appear in a taskbar is a local state. It never gets propagated back to KWin, and cannot be accessible by other processes..

This can be easily verified by having multiple taskbar widgets. Reordering windows in one taskbar doesn't affect other taskbars. 

This really hurts for Monocle layout, because cycling through windows blindly is unproductive.

**Comment by zyf0330** [comment]
Appreciate for your job.
